const config = {
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NjJjYTA0YTdkMDNiOGRlY2M4OWRmNiIsIm5hbWUiOiJNZWxvIiwicm9sZXMiOltdLCJzY29wZXMiOltdLCJpYXQiOjE3MTgxMjE3MDEsImV4cCI6MTcxODIxMDEwMX0.jDdzIqkyPPObbOn-cohTw2q_yNzk1oVXIdZSKcCeAyc",
}

export default config;